config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
# from django.shortcuts import redirect
from django.views import defaults as default_views

# GesFipe
from gesfipe.manageweboob.models import WeboobModules
from gesfipe.banksandaccounts.views import banks_and_accounts_list

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='banksandaccounts/banks_and_accounts_list.html'), name='home'),
    # url(r'^$', TemplateView.as_view(template_name='banksandaccounts/banks_and_accounts_list.html'), name='index'),
    url(r'^$', banks_and_accounts_list),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('gesfipe.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


    # Your stuff: custom urls includes go here
    # url(r'^managegesfi/', include('gesfipe.managegesfi.urls')),
    # url(r'^categories/', include('gesfipe.categories.urls')),
    # url(r'^', include('gesfipe.manageweboob.urls')),
    url(r'^manageweboob/', include('gesfipe.manageweboob.urls')),
    url(r'^managegesfi/', include('gesfipe.managegesfi.urls')),
    url(r'^categories/', include('gesfipe.categories.urls')),
    url(r'^banksandaccounts/', include('gesfipe.banksandaccounts.urls', namespace='banksandaccounts')),


    # path('', include(('gesfipe.banksandaccounts.urls', 'banksandaccounts'), namespace='banksandaccounts')),
    # path('', include('gesfipe.banksandaccounts.urls', namespace='banksandaccounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

gesfipe/banksandaccounts/urls.py
# Django
from django.conf.urls import url
from django.urls import path

# GesFiPe
from . import views

#TODO: Mettre à jour de Django 2.0

app_name = 'banksandaccounts'

urlpatterns = [

    url(r'^$', views.banks_and_accounts_list, name='home'),

    #    url(r'^keywords/(?P<tag_name>[a-z,\',\*,A-Z]+)/$',
    #    views.transactions_with_tag, name='transactions_with_tag'),



    url(r'^transactions_list/$', views.transactions_list, name='transactions_list'),
    url(r'^toto/$', views.TransactionsListView.as_view(), name='transactions_list3'),

    # url(r'^toto/$', views.transactions_list2, name='transactions_list2'),
    # url(r'^$', views.TransactionsListView.as_view(), name='transactions_list'),

    url(r'^bank_detail/(?P<bank_id>[0-9]+)/$', views.bank_detail, name='bank_detail'),
    url(r'^bank_edit/(?P<pk>[0-9]+)/$', views.bank_edit, name='bank_edit'),
    url(r'^bank_create/$', views.bank_create, name='bank_create'),
    url(r'^banks_list/$', views.banks_list, name='banks_list'),

    url(r'^account_detail/(?P<account_id>[0-9]+)/$', views.account_detail, name='account_detail'),
    url(r'^account_edit/(?P<pk>[0-9]+)/$', views.account_edit, name='account_edit'),
    url(r'^account_create/$', views.account_create, name='account_create'),
    url(r'^accounts_list/$', views.AccountListView.as_view(), name='accounts_list'),

    url(r'^transaction_detail/(?P<transaction_id>[0-9]+)/$', views.transaction_detail, name='transaction_detail'),
    url(r'^transaction_edit/(?P<pk>[0-9]+)/$', views.transaction_edit, name='transaction_edit'),
    url(r'^transaction_create/$', views.transaction_create, name='transaction_create'),

    # Not used for the moment
    # url(r'load_transactions/$', views.load_transactions, name='load_transactions'),

    url(r'^account/(?P<account_id>[0-9]+)/$', views.account_list, name='account_list'),
    url(r'^banks_and_accounts_list/$', views.banks_and_accounts_list, name='banks_and_accounts_list'),

    path('banks/<int:pk>/delete/', views.BankDelete.as_view(), name='bank_delete'),
    # url(r'^banks/(?P<pk>[0-9]+)/delete/$', views.BankDelete.as_view(), name='bank_delete'),
    path('banks/connection_and_loading/<int:pk>/',views.bank_connection_and_load_transactions, name='bank_connection_and_load_transactions'),
    path('banks/create_with_weboob_module/<int:pk>', views.bank_create_with_weboob_module, name='bank_create_with_weboob_module'),
]

gesfipe/categories/urls.py
from django.conf.urls import url

from .views import *

# TODO: Mettre à jour en fonction de Django 2.0

app_name = 'categories'

urlpatterns = [
    #    url(r'^$', 'categories.views.category_list', name='category_list'),
    url(r'^category/(?P<node>.+)/$', show_category, name='show_category'),
    # url(r'^category/(?P<hierarchy>.+)/$', show_category, name='show_category'),

    #    url(r'^category/(?P<hierarchy>)/$', show_category, name='category'),

    url(r'^budget/$', category_list, name='budget'),
    url(r'^test/$', category_json, name='categories_json'),

    url(r'^tags/search_tags/$', search_tags, name='search_tags'),

    url(r'^tag_edit/(?P<pk>)$', tag_edit, name='tag_edit'),
    url(r'^tag_edit/(?P<pk>[0-9]+)/$', tag_edit, name='tag_edit'),

    url(r'^category_create/$', category_create, name='category_create'),
    # url(r'^category_edit/(?P<pk>\d+)/$', category_edit, name='category_edit'),
    url(r'^category_edit/(?P<pk>[0-9]+)/$', category_edit, name='category_edit'),

]

gesfipe/managegesfi/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import search as search_views
from .views import *

from django.contrib import admin
#from controlcenter.views import controlcenter

# TODO: to adapt to Django 2.0

app_name = 'managegesfi'

urlpatterns = [
    url(r'search/$', search_views, name='search'),
    url(r'display_meta/$', display_meta, name='display_meta'),

    # TODO: To delete following url 'info_to_print'
    url(r'^info_to_print/(?P<pk>[0-9]+)/$', connect_bank, name='info_to_print'),

    url(r'transactions_by_category/search_categories/$', tag_category_edit, name='tag_category_edit'),
    url(r'^transactions_by_category/(?P<pk>)$', transactions_by_category, name='transactions_by_category'),
    url(r'^transactions_by_category/(?P<pk>[0-9]+)/$', transactions_by_category, name='transactions_by_category'),

    # url(r'list_of_available_banks/$', get_list_of_managed_banks, name='get_list_of_managed_banks'),
    url(r'list_of_available_accounts/$', get_list_of_available_accounts, name='get_list_of_available_accounts'),
    url(r'load_transactions/$', load_transactions, name='load_transactions'),
    url(r'list_unique_numbers/$', list_unique_numbers, name='list_unique_numbers'),

]

gesfipe/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

gesfipe/managegesfi/models.py
from django.db import models

# Create your models here.

gesfipe/manageweboob/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class WeboobModules(models.Model):
    name_of_module = models.CharField(
        'Nom du module',
        default='Nom du module',
        max_length=256)

    description_of_module = models.CharField(
        'Description du module',
        default='Description',
        max_length=256)

    # is_in_database = models.BooleanField(False)
    is_in_database = models.BooleanField(
        False,
        default=False
    )

    def __str__(self):
        return "%s" % self.name_of_module

    class Meta:
        verbose_name = _('weboob module')
        verbose_name_plural = _('weboob modules')
        ordering = ['name_of_module']

gesfipe/categories/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from .models import Tag
from gesfipe.categories.models import Category


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('tag', 'is_new_tag', 'will_be_used_as_tag', 'category',)

    # widgets = {
    #            'category':TreeNodeChoiceField(queryset=Category.objects.all()),
    #        }
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())
    category = TreeNodeChoiceField(queryset=Category.objects.all(), level_indicator=u'+--')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = {'name', 'description', 'amount'}

gesfipe/categories/views.py
from django.shortcuts import render

# Create your views here.

# from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required

# from .models import Category
from gesfipe.banksandaccounts.models import *
from .models import *
from .forms import TagForm, CategoryForm


# Create your views here.


def category_list(request):
    categories = Category.objects.all()
    jsondata = serializers.serialize('json', categories)
    context = {'categories': categories, 'jsondata': jsondata}
    return render(request, 'categories/categories_list.html', context)


def category_json(request):
    categories = Category.objects.all()
    return HttpResponse(serializers.serialize('json', categories), content_type="application/json")


LIST_HEADERS_SEARCH_TAGS = (
    ('Name', 'tag'),
    ('New Tag', 'is_new_tag'),
    ('Used as Tag', 'will_be_used_as_tag'),
    ('Category', 'category'),
)


@login_required
def search_tags(request):
    '''
    Gives the list of tags in transaction key_words not associated with a category (tag.is_new_tag = True)
    :param request:
    :return: render
    '''

    sort_headers = SortHeaders(request, LIST_HEADERS_SEARCH_TAGS)
    transaction_list = Transactions.objects.all()
    list_of_tags = Tag.objects.all()

    listoftags = list()
    listoftags_found = list()

    if list_of_tags:
        for t in list_of_tags:
            t.tag.upper()  # In case we forgot to upperize at the very first time
            # t.is_new_tag = False   #Complicated to manage when updating/changing page
            # TODO: to automize new/old Tag without searching each time "new Tags"
            t.save()
            listoftags.append(t.tag)

    for transaction in transaction_list:
        if not transaction.key_words:  # if key_words is empty, we create key_words
            transaction.create_key_words()
            transaction.save()

        for key_tag in transaction.key_words:
            if key_tag not in listoftags_found:
                key_tag.strip(',') # To verify if it's needed to strip ',' (?)
                listoftags_found.append(key_tag)

    # To get a list unique
    # listoftags_found = set(listoftags_found)

    # Back to a list
    # listoftags_found = list(listoftags_found)

    for tag_found in listoftags_found:
        if tag_found not in listoftags:
            tag = Tag()
            tag.tag = tag_found
            tag.is_new_tag = True
            tag.will_be_used_as_tag = True
            listoftags.append(tag_found)
            tag.save()
            # listoftags.sort()

    listtagnew = Tag.objects.order_by(sort_headers.get_order_by()).filter(is_new_tag=True)
    #    listtagnew = Tag.objects.order_by(sort_headers.get_order_by())

    list_of_headers = list(sort_headers.headers())

    context = {
        "listtagnew": listtagnew,
        'headers': list_of_headers,
    }

    return render(request, 'categories/search_tags.html', context)


LIST_HEADERS_EDIT_TAG = (
    ('Date', 'date_of_transaction'),
    ('Type', 'type_of_transaction'),
    ('Name', 'name_of_transaction'),
    ('Amount', 'amount_of_transaction'),
)


@login_required
def tag_edit(request, pk):
    sort_headers = SortHeaders(request, LIST_HEADERS_EDIT_TAG)
    tags_list = Tag.objects.filter(will_be_used_as_tag=True)

    if pk == '':
        transactions = Transactions.objects.order_by(sort_headers.get_order_by())
        tag = None
    else:
        tag = get_object_or_404(Tag, pk=pk)
        transactions = Transactions.objects.order_by(sort_headers.get_order_by()).filter(
            name_of_transaction__icontains=tag.tag)

    if request.method == "POST":
        form = TagForm(request.POST, instance=tag)

        if form.is_valid():
            tag = form.save(commit=False)
            tag.is_new_tag = False
            tag.will_be_used_as_tag = True
            tag.save()
            return redirect('tag_edit', pk=tag.pk)
    else:
        form = TagForm(instance=tag)

    list_of_headers = list(sort_headers.headers())

    context = {
        'transactions': transactions,
        'tags_list': tags_list,
        'tag': tag,
        'form': form,
        'headers': list_of_headers,
    }
    return render(request, 'categories/tag_edit.html', context)


@login_required
def show_category(request, node=None):
    cats = Category.objects.all()
    node = node.split('/')
    # print("NNNNNNNNNN OOOOOOOOO DDDDDDDDDDD EEEEEEEEEEEE: {}".format(node))
    if node[-1] == 'None':
        current = Category.objects.filter(parent=None)
        # print("Current: {} \n".format(current))
        ancestors = Category.objects.filter(parent=None)
        # ancestors = None
        # print("Ancestors: {} \n".format(current))

        # children = Category.objects.filter(parent=ancestors[0])
        children = Category.objects.filter(parent=None)
        # children = Category.objects.filter(parent=ancestors)

        # print("Children: {} \n".format(current))

    else:
        current = Category.objects.filter(name=node[-1])
        children = Category.objects.filter(parent__name=node[-1])
        ancestors = current.get_ancestors()

        if not ancestors:
            ancestors = current
        else:
            ancestors = current.get_ancestors(include_self=True)

    return render(request, 'categories/categories.html',
                  {'cats': cats,
                   'ancestors': ancestors,
                   'children': children,
                   'current': current,
                   })


@login_required
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            # category.owner = request.user
            category.save()
            # form.save_m2m()
            return redirect('categories:show_category')
    else:
        form = CategoryForm()
    context = {'form': form, 'create': True}
    return render(request, 'categories/category_edit.html', context)


@login_required
def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    cats = Category.objects.all()
    # if bookmark.owner != request.user and not request.user.is_superuser:
    #     raise PermissionDenied
    if request.method == 'POST':
        form = CategoryForm(instance=category, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('categories:show_category', node=category.parent.name)
            # return redirect('budget')
    else:
        form = CategoryForm(instance=category)
    context = {'cats': cats, 'form': form, 'create': False}
    return render(request, 'categories/category_edit.html', context)

gesfipe/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

gesfipe/templates/ManageGesfi/partial_results_menu.html
{% load i18n %}

<div class="list-group"
     data-toggle="tooltip"
     data-placement="top"
     title="Gives a synthesis of the research's results with the number of occurrences find in data of banks, accounts, transactions and categories. Just click on fields to access found data. ">
    <div
       class="list-group-item active">
        <span>{% trans 'Number of result(s) found in :' %}</span>
    </div>
    <a href="{% url 'managegesfi:search' %}?q={{ querystring }}&type=banks"
       class="list-group-item{% if active == 'banks' %} list-group-item-primary{% endif %}">
        <span>{% trans 'Banks' %}</span>
        <span class="badge">{{ count.banks }}</span>
    </a>
    <a href="{% url 'managegesfi:search' %}?q={{ querystring }}&type=accounts"
       class="list-group-item{% if active == 'accounts' %} list-group-item-primary{% endif %}">
        <span>{% trans 'Accounts' %}</span>
        <span class="badge">{{ count.accounts }}</span>
    </a>
    <a href="{% url 'managegesfi:search' %}?q={{ querystring }}&type=transactions"
       class="list-group-item{% if active == 'transactions' %} list-group-item-primary{% endif %}">
        <span>{% trans 'Transactions' %}</span>
        <span class="badge">{{ count.transactions }}</span>
    </a>
    <a href="{% url 'managegesfi:search' %}?q={{ querystring }}&type=categories"
       class="list-group-item{% if active == 'categories' %} list-group-item-primary{% endif %}">
        <span>{% trans 'Categories' %}</span>
        <span class="badge">{{ count.categories }}</span>
    </a>
</div>

gesfipe/templates/ManageGesfi/partial_transactions_results.html
{% load i18n %}

{% if results %}

<!-- <div class="list-group"> -->
    <table class="table table-hover table-responsive table-bordered table-striped table-condensed">
        <thead>
          <tr>
              <th>{% trans 'Date' %}</th>
              <th>{% trans 'Type' %}</th>
              <th>{% trans 'Name' %}</th>
              <th>{% trans 'Amount' %}</th>
              <th>{% trans 'Currency' %}</th>
              <th>{% trans 'N° Account' %}</th>
          </tr>
        </thead>
        <tbody>
        {% for transaction in results %}
        <tr>
            <td>{{ transaction.date_of_transaction|date:" Y/m/d" }}</td>
            <td>{{ transaction.type_of_transaction }}</td>
            {# <td><a href="/transaction_detail/{{transaction.id}}/"> {{ transaction.name_of_transaction }} </a></td> #}
            <td><a href="{% url 'banksandaccounts:transaction_detail' transaction.id %}"> {{ transaction.name_of_transaction }} </a></td>
            {% if transaction.amount_of_transaction >= 0 %}
                <td class="font-blue"> {{ transaction.amount_of_transaction | rjust:"10" }} </td>
            {% else %}
                <td class="font-red"> {{ transaction.amount_of_transaction | rjust:"10" }} </td>
            {% endif %}
            <td>{{ transaction.currency_of_transaction }}</td>
            <td>{{ transaction.account.num_of_account }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
<!-- </div> -->

{% else %}
    <h4 class="no-result">{% trans 'No transactions found' %} :(</h4>
{% endif %}

gesfipe/templates/ManageGesfi/results.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %} - {% trans 'Search results' %} {% endblock %}

{% block head %}
    <link href="{% static 'css/search.css' %}" rel="stylesheet">
    <script src="{% static 'js/search.js' %}"></script>
{% endblock head %}

{% block heading %}
    <h2>{% trans 'Search' %} </h2>
{% endblock heading %}

<!-- TODO: To change position of "row result" (with using block sidebar) -->
{% block content %}
    <div class="row">
        <div class="col-md-3">
            <!-- This "div" tag just to keep align form below and the results under research area -->
        </div>
        <div class="col-md-9">
            <form class="search-sidebar" role="search" action="{% url 'managegesfi:search' %}">
                <input type="hidden" name="type" value="{{ active }}">
                <div class="input-group">
                    <input type="text" class="form-control" name="q"
                           placeholder="{% trans 'Search into : Banks, Accounts, Transactions and Categories' %}"
                           value="{{ querystring }}">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-primary search-sidebar">
                          Submit
                          <!-- <span class="glyphicon glyphicon-search"> </span> -->
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div class="row results">
        <div class="col-md-3">
            {% include 'ManageGesfi/partial_results_menu.html' with active=active count=count querystring=querystring %}
        </div>
        <div class="col-md-9">
            {% if active == 'banks' %}
                {% include 'ManageGesfi/partial_banks_results.html' with results=results %}
            {% elif active == 'accounts' %}
                {% include 'ManageGesfi/partial_accounts_results.html' with results=results %}
            {% elif active == 'transactions' %}
                {% include 'ManageGesfi/partial_transactions_results.html' with results=results %}
            {% elif active == 'categories' %}
                {% include 'ManageGesfi/partial_categories_results.html' with results=results %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

gesfipe/templates/ManageGesfi/table_header.html
{% for header in headers %}<th{{ header.class_attr }}>
  {% if header.sortable %}<a href="{{ header.url|escape }}">{% endif %}
    {{ header.text }}
  {% if header.sortable %}</a>{% endif %}
</th>{% endfor %}

gesfipe/templates/ManageGesfi/tag_category.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load mptt_tags %}

{% block title %}
    {% trans 'Tags and Categories' %}
{% endblock %}


{% block heading %}
    <h2>{% trans 'Categories with tags' %} </h2>
    <p><i>Lists transactions by categories</i>  </p>
{% endblock heading %}


{% block content %}
    {% for category in categories_list %}
    <br><h3>{{category}}</h3><br>
            <table class="table table-striped ">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Name</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                    {% if transaction.category_of_transaction.name == category.name %}
                    <tr>
                        <td>{{ transaction.date_of_transaction|date:" Y/m/d" }}</td>
                        <td>{{ transaction.type_of_transaction }}</td>
                        <td><a href="/transaction_detail/{{transaction.id}}/"> {{ transaction.name_of_transaction }} </a> </td>
                        {% if transaction.amount_of_transaction >= 0 %}
                            <td class="font-blue"> {{ transaction.amount_of_transaction | rjust:"10" }} </td>
                        {% else %}
                            <td class="font-red"> {{ transaction.amount_of_transaction | rjust:"10" }} </td>
                        {% endif %}
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}

{% endblock %}


{% block sidebar %}
    <div class="row">
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'managegesfi:transactions_by_category' pk=Null %}"> Categories</a>
            <ul>
                {% recursetree categories_list %}
                <li>
                    <!-- <a href="{{ node.name }}">{{ node.name }}</a> -->
                    <a href="{% url 'managegesfi:transactions_by_category' pk=node.pk %}">{{ node.name }}</a>
                    {% if not node.is_leaf_node %}
                        <ul class="children">
                            {{ children }}
                        </ul>
                    {% endif %}
                </li>
                {% endrecursetree %}
            </ul>
        </div>
    </div>
{% endblock %}

gesfipe/templates/ManageGesfi/transactions_by_category.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load mptt_tags %}

{% block title %}
    {% trans 'Transactions with categories' %}
{% endblock %}

{% block heading %}
    <h2>{% trans 'Transactions with categories' %} </h2>
    <p><i>List of transactions by category</i>  </p>
{% endblock heading %}

{% block content %}
    <ul class="breadcrumb">
    {% for i in ancestors %}
        <li><a href="{% url 'managegesfi:transactions_by_category' pk=i.pk %}"> {{ i.name }} </a></li>
    {% endfor %}
    </ul>

    {% regroup transactions by category_of_transaction as category_list %}
    {% for category in category_list %}
    <h3>{{category.grouper}}</h3><br>
        {% if category.grouper == None %}
            <i> Transactions without category are not presented on this page</i>
        {% else %}
                <table class="table table-striped ">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Name</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in category.list %}
                        <tr>
                            <td>{{ transaction.date_of_transaction|date:" Y/m/d" }}</td>
                            <td>{{ transaction.type_of_transaction }}</td>
                            <td><a href="/transaction_detail/{{transaction.id}}/"> {{ transaction.name_of_transaction }} </a> </td>
                            {% if transaction.amount_of_transaction >= 0 %}
                                <td class="font-blue"> {{ transaction.amount_of_transaction | rjust:"10" }} </td>
                            {% else %}
                                <td class="font-red"> {{ transaction.amount_of_transaction | rjust:"10" }} </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block sidebar %}

    <!-- <div class="row"> -->
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'managegesfi:transactions_by_category' pk=Null %}"> Transactions by Category</a>
                <ul>
                    {% recursetree categories %}
                        <li>
                            <a href="{% url 'managegesfi:transactions_by_category' pk=node.pk %}">{{ node.name }}</a>
                            {% if not node.is_leaf_node %}
                                <ul class="children">
                                    {{ children }}
                                </ul>
                            {% endif %}
                        </li>
                    {% endrecursetree %}
            </ul>
        </div>
    <!--
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'transactions_by_category' pk=Null %}"> Categories</a>
            {% for category in categories|dictsort:"name"  %}
                <a class="list-group-item" href="{% url 'transactions_by_category' pk=category.pk %}"> {{category.name}}</a>
            {% endfor %}
        </div>
    -->
    <!-- </div> -->
{% endblock %}