config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
# from django.shortcuts import redirect
from django.views import defaults as default_views

# GesFipe
from gesfipe.manageweboob.models import WeboobModules
from gesfipe.banksandaccounts.views import banks_and_accounts_list

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='banksandaccounts/banks_and_accounts_list.html'), name='home'),
    # url(r'^$', TemplateView.as_view(template_name='banksandaccounts/banks_and_accounts_list.html'), name='index'),
    url(r'^$', banks_and_accounts_list),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('gesfipe.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


    # Your stuff: custom urls includes go here
    # url(r'^managegesfi/', include('gesfipe.managegesfi.urls')),
    # url(r'^categories/', include('gesfipe.categories.urls')),
    # url(r'^', include('gesfipe.manageweboob.urls')),
    url(r'^manageweboob/', include('gesfipe.manageweboob.urls')),
    url(r'^managegesfi/', include('gesfipe.managegesfi.urls')),
    url(r'^categories/', include('gesfipe.categories.urls')),
    url(r'^banksandaccounts/', include('gesfipe.banksandaccounts.urls', namespace='banksandaccounts')),


    # path('', include(('gesfipe.banksandaccounts.urls', 'banksandaccounts'), namespace='banksandaccounts')),
    # path('', include('gesfipe.banksandaccounts.urls', namespace='banksandaccounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

gesfipe/categories/urls.py
from django.conf.urls import url

from .views import *

# TODO: Mettre à jour en fonction de Django 2.0

app_name = 'categories'

urlpatterns = [
    #    url(r'^$', 'categories.views.category_list', name='category_list'),
    url(r'^category/(?P<node>.+)/$', show_category, name='show_category'),
    # url(r'^category/(?P<hierarchy>.+)/$', show_category, name='show_category'),

    #    url(r'^category/(?P<hierarchy>)/$', show_category, name='category'),

    url(r'^budget/$', category_list, name='budget'),
    url(r'^test/$', category_json, name='categories_json'),

    url(r'^tags/search_tags/$', search_tags, name='search_tags'),

    url(r'^tag_edit/(?P<pk>)$', tag_edit, name='tag_edit'),
    url(r'^tag_edit/(?P<pk>[0-9]+)/$', tag_edit, name='tag_edit'),

    url(r'^category_create/$', category_create, name='category_create'),
    # url(r'^category_edit/(?P<pk>\d+)/$', category_edit, name='category_edit'),
    url(r'^category_edit/(?P<pk>[0-9]+)/$', category_edit, name='category_edit'),

]

gesfipe/managegesfi/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import search as search_views
from .views import *

from django.contrib import admin
#from controlcenter.views import controlcenter

# TODO: to adapt to Django 2.0

app_name = 'managegesfi'

urlpatterns = [
    url(r'search/$', search_views, name='search'),
    url(r'display_meta/$', display_meta, name='display_meta'),

    # TODO: To delete following url 'info_to_print'
    url(r'^info_to_print/(?P<pk>[0-9]+)/$', connect_bank, name='info_to_print'),

    url(r'transactions_by_category/search_categories/$', tag_category_edit, name='tag_category_edit'),
    url(r'^transactions_by_category/(?P<pk>)$', transactions_by_category, name='transactions_by_category'),
    url(r'^transactions_by_category/(?P<pk>[0-9]+)/$', transactions_by_category, name='transactions_by_category'),

    # url(r'list_of_available_banks/$', get_list_of_managed_banks, name='get_list_of_managed_banks'),
    url(r'list_of_available_accounts/$', get_list_of_available_accounts, name='get_list_of_available_accounts'),
    url(r'load_transactions/$', load_transactions, name='load_transactions'),
    url(r'list_unique_numbers/$', list_unique_numbers, name='list_unique_numbers'),

]

gesfipe/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

gesfipe/managegesfi/models.py
from django.db import models

# Create your models here.

gesfipe/categories/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from .models import Tag
from gesfipe.categories.models import Category


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('tag', 'is_new_tag', 'will_be_used_as_tag', 'category',)

    # widgets = {
    #            'category':TreeNodeChoiceField(queryset=Category.objects.all()),
    #        }
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())
    category = TreeNodeChoiceField(queryset=Category.objects.all(), level_indicator=u'+--')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = {'name', 'description', 'amount'}

gesfipe/banksandaccounts/views.py
# Create your views here.

# Python
import logging

# from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect, render

# django
from  django.contrib.auth.hashers import make_password
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Avg, Sum, Min, Max, Count
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Weboob
from weboob.core import Weboob
from weboob.capabilities.bank import CapBank

# Gesfipe
from .forms import *
from gesfipe.categories.models import Tag
from gesfipe.managegesfi.views import list_unique_of_numbers


logger = logging.getLogger(__name__)

# Create your views here.
'''
def accounts_info(account_id=0):
    if account_id == 0:
        account_info = Accounts.objects.annotate(
            total_amount_by_account=Sum('transactions__amount_of_transaction'),
            avg_amount_by_account=Avg('transactions__amount_of_transaction'),
            min_amount_by_account=Min('transactions__amount_of_transaction'),
            max_amount_by_account=Max('transactions__amount_of_transaction'),
            num_transac_by_account=Count('transactions'))

    elif account_id != 0:
        account_info = Accounts.objects.filter(id=account_id).annotate(
            total_amount_by_account=Sum('transactions__amount_of_transaction'),
            avg_amount_by_account=Avg('transactions__amount_of_transaction'),
            min_amount_by_account=Min('transactions__amount_of_transaction'),
            max_amount_by_account=Max('transactions__amount_of_transaction'),
            num_transac_by_account=Count('transactions'))

    return account_info


def accounts_info2(request, account_id=0):
    account_info = Accounts.objects.filter(owner_of_account=request.user).annotate(
    total_amount_by_account=Sum('transactions__amount_of_transaction'),
    avg_amount_by_account=Avg('transactions__amount_of_transaction'),
    min_amount_by_account=Min('transactions__amount_of_transaction'),
    max_amount_by_account=Max('transactions__amount_of_transaction'),
    num_transac_by_account=Count('transactions'))

    return account_info
'''


def accounts_info2(request, account_id=0):
    if account_id == 0:
        account_info = Accounts.objects.filter(owner_of_account=request.user).annotate(
            total_amount_by_account=Sum('transactions__amount_of_transaction'),
            avg_amount_by_account=Avg('transactions__amount_of_transaction'),
            min_amount_by_account=Min('transactions__amount_of_transaction'),
            max_amount_by_account=Max('transactions__amount_of_transaction'),
            num_transac_by_account=Count('transactions'))

    elif account_id != 0:
        account_info = Accounts.objects.filter(owner_of_account=request.user).filter(id=account_id).annotate(
            total_amount_by_account=Sum('transactions__amount_of_transaction'),
            avg_amount_by_account=Avg('transactions__amount_of_transaction'),
            min_amount_by_account=Min('transactions__amount_of_transaction'),
            max_amount_by_account=Max('transactions__amount_of_transaction'),
            num_transac_by_account=Count('transactions'))

    return account_info


@login_required
def banks_and_accounts_list(request):
    banks_list = Banks.objects.all()  # .filter(accounts__owner_of_account=request.user)
    accounts_list = Accounts.objects.all().filter(owner_of_account=request.user)
    account_total = \
        Transactions.objects.filter(account__owner_of_account=request.user).aggregate(
            total=Sum('amount_of_transaction'))

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'banks_list': banks_list,
        'accounts_list': accounts_list,
        'account_total': account_total,
        'accounts_info': accounts_info2(request),
        'num_visits': num_visits,
    }
    return render(
        request,
        'banksandaccounts/banks_and_accounts_list.html',
        context
    )


@login_required
def transactions_list(request):
    # banks = Banks.objects.all()
    banks_list = Banks.objects.all()  # .filter(accounts__owner_of_account=request.user)
    # accounts_list = Accounts.objects.all().filter(owner_of_account=request.user)

    # transaction_list = Transactions.objects.all()
    transaction_list = Transactions.objects.filter(account__owner_of_account=request.user)

    account_total = transaction_list.aggregate(Sum('amount_of_transaction'))

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Page de 25 lignes
    num_of_lines_per_page = 25
    paginator = Paginator(transaction_list, num_of_lines_per_page)
    page = request.GET.get('page')

    try:
        transactions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        transactions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        transactions = paginator.page(paginator.num_pages)

    logger.warning('In transaction_list : %s', transactions)

    context = {
        'banks_list': banks_list,
        # used for dispatching accounts by bank in sidebar

        'transactions': transactions,
        # used to list transactions related to account(s) with num_of_lines_per_page

        'account_total': account_total,
        # sum of all transactions

        'accounts_info': accounts_info2(request, 0),
        # general information related to all accounts (due to "0")

        'all_accounts': accounts_info2(request, 0),
        # general information related
        # to all accounts (due to "0") and used in sidebar

        'num_visits': num_visits,
        # to count the number of visit on the main page (transactions_list2.html only)
        # just for test to use django.sessions middleware
    }
    return render(request, 'banksandaccounts/transactions_list.html', context)


# TODO: Access management ==> to be improved with ListView
# class TransactionsListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
class TransactionsListView(LoginRequiredMixin, generic.ListView):
    model = Transactions
    paginate_by = 25

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TransactionsListView, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['account_total'] = Transactions.objects.aggregate(Sum('amount_of_transaction'))
        # context['banks'] = Banks.objects.all()
        context['banks'] = Banks.objects.all().filter(accounts__owner_of_account=self.request.user)
        # context['accounts_info'] = accounts_info(0)
        context['accounts_info'] = accounts_info2(self.request, 0)
        # context['all_accounts'] = accounts_info(0)
        context['all_accounts'] = accounts_info2(self.request, 0)

        return context

    def get_queryset(self):
        return Transactions.objects.filter(account__owner_of_account=self.request.user)

    context_object_name = 'transactions_list'  # your own name for the list as a template variable
    queryset = Transactions.objects.all()  # [:55] Get 55 transactions
    template_name = 'banksandaccounts/transactions_list3.html'  # Specify your own template name/location


@login_required
def account_list(request, account_id):
    # accounts = Accounts.objects.all()
    banks_list = Banks.objects.all()
    # banks = Banks.objects.all().filter(accounts__owner_of_account=request.user)

    transac_list = Transactions.objects.filter(account_id=account_id).order_by('-real_date_of_transaction', 'name_of_transaction')
    # transactions_list = Transactions.objects.get(id=account_id)

    account_total = Transactions.objects.filter(account_id=account_id).aggregate(Sum('amount_of_transaction'))

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Page de 25 lignes
    num_of_lines_per_page = 50
    paginator = Paginator(transac_list, num_of_lines_per_page)
    page = request.GET.get('page')

    try:
        transactions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        transactions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        transactions = paginator.page(paginator.num_pages)

    context = {
        'banks_list': banks_list,
        # used for dispatching accounts by bank in sidebar

        'transactions': transactions,
        # used to list transactions related to account(s)

        'account_total': account_total,
        # sum of all transactions

        'accounts_info': accounts_info2(request, account_id),
        # general information related to selectede account

        'all_accounts': accounts_info2(request, 0),
        # general information related to all accounts (due to "0") and used in sidebar

        'num_visits': num_visits,
        # to count the number of visit on the main page (transactions_list2.html only)
        # just for test to use django.sessions middleware

    }

    return render(request, 'banksandaccounts/transactions_list.html', context)


class BankUpdate(LoginRequiredMixin, UpdateView):
    model = Banks
    fields = ['name_of_bank', 'num_of_bank', 'bank_login', 'bank_password', 'module_weboob' ]


class BankDelete(LoginRequiredMixin, DeleteView):
    model = Banks
    # TODO: to redirect sommewhere else (obligé de resélectionner la banque pour qu'elle soit supprimée)

gesfipe/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

gesfipe/templates/categories/categories.html
{% extends 'base.html' %}
{% load mptt_tags %}
{% load i18n %}

{% block head_title %}  {% endblock %}

{% block title %}
    {% trans 'Categories' %}
{% endblock %}

{% block content %}

  <ol class="breadcrumb">
      {% for i in ancestors %}
          <li class="breadcrumb-item active"><a href="{% url 'categories:show_category' node=i.name %}"> {{ i.name }} </a></li>
      {% endfor %}
  </ol>

  {% if children %}
    <div class="list-group">
      <h5 class="list-group-item active">
        Sub Categories of:
          {% for c in current %}
            <br>
            <span>
              <b>
                {{c.name}}
              </b>
            </span>
            <span class="badge badge-pill badge-info pull-right" style="float:right;">
              {{c.amount}}
            </span>
          {% endfor %}
      </h5>
      {% for i in children %}
        {% if i.is_leaf_node %}
          <a href="{% url 'categories:category_edit' pk=i.pk %}" class="list-group-item">
            <span>{{ i.name }}</span>
            <span class="badge badge-pill badge-info" style="float:right;">{{i.amount}}</span>
          </a>
        {% else %}
          <!-- <a href="{{ i.name }}" class="list-group-item"> -->
          <a href="{% url 'categories:show_category' node=i.name %}" class="list-group-item">
            <span>{{ i.name }}</span>
            <span class="badge badge-pill badge-info" style="float:right;">{{i.amount}}</span>
          </a>
        {% endif %}
      {% endfor %}
    </div>
  {% endif %}

{% endblock content %}

{% block sidebar %}
    <!-- <div class="row"> -->
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'managegesfi:transactions_by_category' pk=Null %}"> Categories</a>
            <ul>
                {% recursetree cats %}
                    <li>
                        {% if not node.is_leaf_node %}
                        <a href="{{ node.name }}">{{ node.name }}</a>
                            <ul class="children">
                                {{ children }}
                            </ul>
                        {% else %}
                            <a href="{% url 'categories:category_edit' pk=node.pk %}"> {{ node.name }}</a>
                        {% endif %}
                    </li>
                {% endrecursetree %}
                </ul>
        </div>
    <!-- </div> -->
{% endblock sidebar %}

gesfipe/templates/categories/categories_list.html
{% extends "base.html" %}
{% load mptt_tags %}

{% block title %}Categories{% endblock %}

{% block heading %}
    <h2>Categories</h2>
{% endblock %}

{% block sidebar %} {% endblock sidebar %}

{% block content %}

        <div id="budget_jstree1"  class="list-group">
            <!-- in this example the tree is populated from inline HTML -->

            <ul>
                {% recursetree categories %}
                    <li>
                        {{ node.name }} +=======+    {{ node.amount }}
                        {% if not node.is_leaf_node %}
                            <ul>
                                {{ children }}
                            </ul>
                        {% endif %}
                    </li>
                {% endrecursetree %}
            </ul>


        </div>

        <script>
            $('#budget_jstree1').jstree({
                "core" : {
                   "themes" : {
                        "variant" : "large"
                        }
                      },
                  "checkbox" : {
                         "keep_selected_style" : false},
                        //"plugins" : [ "wholerow", "checkbox" ]
                        "plugins" : [ "wholerow", "contextmenu", "dnd" ]
                });


        </script>



{% endblock %}

gesfipe/templates/categories/categoryDetail.html
{% load namify %}

<ul class="breadcrumbs">
    <li><a href="/">Home</a></li>

    {% for i in instance.get_slug_list_for_categories %}
       <li><a href="/category/{{ i }}">{{ i | get_name }}</a></li>
    {% endfor %}

</ul>

gesfipe/templates/categories/category_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load mptt_tags %}
{% load i18n %}


{% block title %}
    {% if create %}Create{% else %}Edit{% endif %} category {{ form.instance.name }}
{% endblock %}

{% block heading %}
    <h2>
        {% if create %}
            Create category
        {% else %}
            Edit category: <i>{{ form.instance.name }}</i>
        {% endif %}
    </h2>
{% endblock %}

{% block content %}
    {% if create %}
        {% url "category_create" as action_url %}
    {% else %}
        {% url "categories:category_edit" pk=form.instance.pk as action_url %}
    {% endif %}
    <form action="{{ action_url }}" method="post" accept-charset="utf-8">
        {{ form|crispy }}
        {% csrf_token %}
        <p><input type="submit" class="btn btn-default" value="Save"></p>
    </form>
{% endblock %}

{% block sidebar %}
    <!-- <div class="row"> -->
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'managegesfi:transactions_by_category' pk=Null %}"> Categories</a>
            <ul>
                {% recursetree cats %}
                    <li>
                        {% if not node.is_leaf_node %}
                        <a href="{% url 'categories:show_category' node=node.name %}">{{ node.name }}</a>
                            <ul class="children">
                                {{ children }}
                            </ul>
                        {% else %}
                            <a href="{% url 'categories:category_edit' pk=node.pk %}"> {{ node.name }}</a>
                        {% endif %}
                    </li>
                {% endrecursetree %}
                </ul>
        </div>
    <!-- </div> -->
{% endblock sidebar %}

gesfipe/templates/categories/search_tags.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load sort_headers %}


{% block title %} {% trans 'Tags' %} {% endblock %}

{% block head %}
    <link href="{% static 'css/search.css' %}" rel="stylesheet">
    <script src="{% static 'js/search.js' %}"></script>
{% endblock head %}

{% block heading %}
    <h2>{% trans 'New Tags identified:' %} {{listtagnew.count}} </h2>
    <p><i>{% trans "New tags are identified by searching words in all transactions name stored in database. To edit tags, plesae click" %} <a href="{% url 'categories:tag_edit' pk=Null %}"> <u>here</u> </a></i></p>
{% endblock heading %}


{% block content %}
    <div class="list-group">
        <table class="table table-striped">
            <thead>
                <tr>
                    {% table_header headers %}
                </tr>
            </thead>
            <tbody>
                {%if not listtagnew %}
                    <tr>
                        <td>No new Tag</td>
                    </tr>
                {% else %}
                    {% for tag in listtagnew %}
                        <tr>
                            <td>
                                <div>
                                    <label>{{tag.tag}}</label>
                                </div>
                            </td>
                            <td>
                                <div>
                                    {% if tag.is_new_tag == True %}
                                        <label><span class="glyphicon glyphicon-ok"></span></label>
                                    {% else %}
                                        <label><span class="glyphicon glyphicon-star-remove"></span></label>
                                    {% endif %}
                                </div>
                            </td>
                            <td>
                                <div>
                                    {% if tag.will_be_used_as_tag == True %}
                                        <label><span class="glyphicon glyphicon-ok"></span></label>
                                    {% else %}
                                        <label><span class="glyphicon glyphicon-star-remove"></span></label>
                                    {% endif %}
                                </div>
                            </td>
                            <td>
                                <div>
                                    {% if tag.category.name != None %}
                                        {{tag.category.name}}
                                    {% else %}
                                        No associated category
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>

{% endblock content %}

{% block sidebar %}
    <div class="row">
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'categories:tag_edit' pk=Null %}"> Tags</a>
            {% for tag in listtagnew %}
                {% if tag.is_new_tag == False %}
                    <a class="list-group-item font-blue" href="{% url 'categories:tag_edit' pk=tag.pk %}"> {{tag.tag}}</a>
                {% else %}
                    <a class="list-group-item" href="{% url 'categories:tag_edit' pk=tag.pk %}"> {{tag.tag}}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

gesfipe/templates/categories/tag_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load sort_headers %}


{% block title %}
    {% if tag == None %}
        {% trans 'Transactions containing the tag:' %} "No Tag selected"
    {% else %}
        {% trans 'Transactions containing the tag:' %} "{{tag.tag}}"
    {% endif %}
{% endblock %}


{% block heading %}
    {% if tag == None %}
        <h2>{% trans 'Transactions with "No Tag selected"' %} </h2>
        <p><i>Number of transaction(s) with "No Tag selected": {{transactions.count}}. To Edit a tag, please select one on the right side of the screen here below</i>  </p>
    {% else %}
        <h2>{% trans 'Transactions with tag:' %} "{{tag.tag}}" </h2>
        <p><i>Number of transaction(s) containing tag: "{{tag.tag}}": {{transactions.count}}</i>  </p>
    {% endif %}
{% endblock heading %}


{% block content %}
    {% if tag != None %}
        <div class="list-inline">
            <form method="POST" class="tag-form">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        {% for field in form %}
                            <td>
                                {{field.label_tag}}
                                {{field}}
                            </td>
                        {% endfor %}
                        <td><span> <button type="submit" class="save btn btn-primary">Save</button> </span></td>
                    </tr>
                </table>
            </form>
        </div>
    {% endif %}
    <!-- <div class="list-group"> -->
        <table class="table table-striped">
            <thead>
                <tr>
                    {% table_header headers %}
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                    <tr>
                        <td>{{ transaction.date_of_transaction|date:" Y/m/d" }}</td>
                        <td>{{ transaction.type_of_transaction }}</td>
                        <td>{{ transaction.name_of_transaction }}</td>
                        <td>{{ transaction.amount_of_transaction | rjust:"10" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    <!-- </div> -->
{% endblock %}


{% block sidebar %}
    <div class="row">
        <div class="list-group">
            <a class="list-group-item active" href="{% url 'categories:tag_edit' pk=Null %}"> Tags</a>
            {% for tag in tags_list %}
                {% if tag.is_new_tag == False %}
                    <a class="list-group-item font-blue" href="{% url 'categories:tag_edit' pk=tag.pk %}"> {{tag.tag}}</a>
                {% else %}
                    <a class="list-group-item" href="{% url 'categories:tag_edit' pk=tag.pk %}"> {{tag.tag}}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}