config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
# from django.shortcuts import redirect
from django.views import defaults as default_views

# GesFipe
from gesfipe.manageweboob.models import WeboobModules
from gesfipe.banksandaccounts.views import banks_and_accounts_list

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='banksandaccounts/banks_and_accounts_list.html'), name='home'),
    # url(r'^$', TemplateView.as_view(template_name='banksandaccounts/banks_and_accounts_list.html'), name='index'),
    url(r'^$', banks_and_accounts_list),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('gesfipe.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


    # Your stuff: custom urls includes go here
    # url(r'^managegesfi/', include('gesfipe.managegesfi.urls')),
    # url(r'^categories/', include('gesfipe.categories.urls')),
    # url(r'^', include('gesfipe.manageweboob.urls')),
    url(r'^manageweboob/', include('gesfipe.manageweboob.urls')),
    url(r'^managegesfi/', include('gesfipe.managegesfi.urls')),
    url(r'^categories/', include('gesfipe.categories.urls')),
    url(r'^banksandaccounts/', include('gesfipe.banksandaccounts.urls', namespace='banksandaccounts')),


    # path('', include(('gesfipe.banksandaccounts.urls', 'banksandaccounts'), namespace='banksandaccounts')),
    # path('', include('gesfipe.banksandaccounts.urls', namespace='banksandaccounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

gesfipe/categories/urls.py
from django.conf.urls import url

from .views import *

# TODO: Mettre à jour en fonction de Django 2.0

app_name = 'categories'

urlpatterns = [
    #    url(r'^$', 'categories.views.category_list', name='category_list'),
    url(r'^category/(?P<node>.+)/$', show_category, name='show_category'),
    # url(r'^category/(?P<hierarchy>.+)/$', show_category, name='show_category'),

    #    url(r'^category/(?P<hierarchy>)/$', show_category, name='category'),

    url(r'^budget/$', category_list, name='budget'),
    url(r'^test/$', category_json, name='categories_json'),

    url(r'^tags/search_tags/$', search_tags, name='search_tags'),

    url(r'^tag_edit/(?P<pk>)$', tag_edit, name='tag_edit'),
    url(r'^tag_edit/(?P<pk>[0-9]+)/$', tag_edit, name='tag_edit'),

    url(r'^category_create/$', category_create, name='category_create'),
    # url(r'^category_edit/(?P<pk>\d+)/$', category_edit, name='category_edit'),
    url(r'^category_edit/(?P<pk>[0-9]+)/$', category_edit, name='category_edit'),

]

gesfipe/managegesfi/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import search as search_views
from .views import *

from django.contrib import admin
#from controlcenter.views import controlcenter

# TODO: to adapt to Django 2.0

app_name = 'managegesfi'

urlpatterns = [
    url(r'search/$', search_views, name='search'),
    url(r'display_meta/$', display_meta, name='display_meta'),

    # TODO: To delete following url 'info_to_print'
    url(r'^info_to_print/(?P<pk>[0-9]+)/$', connect_bank, name='info_to_print'),

    url(r'transactions_by_category/search_categories/$', tag_category_edit, name='tag_category_edit'),
    url(r'^transactions_by_category/(?P<pk>)$', transactions_by_category, name='transactions_by_category'),
    url(r'^transactions_by_category/(?P<pk>[0-9]+)/$', transactions_by_category, name='transactions_by_category'),

    # url(r'list_of_available_banks/$', get_list_of_managed_banks, name='get_list_of_managed_banks'),
    url(r'list_of_available_accounts/$', get_list_of_available_accounts, name='get_list_of_available_accounts'),
    url(r'load_transactions/$', load_transactions, name='load_transactions'),
    url(r'list_unique_numbers/$', list_unique_numbers, name='list_unique_numbers'),

]

gesfipe/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

gesfipe/banksandaccounts/models.py
# Python
from binascii import crc32
import re
import datetime

# Django
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

# WeBoob
from weboob.capabilities.base import empty
from weboob.tools.compat import unicode

# GesFiPe
from gesfipe.manageweboob.models import WeboobModules
from gesfipe.categories.models import Category
from gesfipe.users.models import User



class Banks(models.Model):
    name_of_bank = models.CharField(
        'Name of Bank',
        default='Name of Bank',
        max_length=256
    )

    num_of_bank = models.CharField(
        'Id of Bank',
        default='Id',
        max_length=256
    )

    bank_login = models.CharField(
        'Login',
        blank=True,
        max_length=64
    )

    bank_password = models.CharField(
        'Password',
        blank=True,
        max_length=512
    )

    # TODO: Plutôt prévoir une ForeignKey to modules weboob database ?
    # module_weboob = models.CharField(
    #     'Bank module',
    #     blank=True,
    #     null=True,
    #     max_length=64
    # )

    module_weboob = models.ForeignKey(
        WeboobModules,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def get_weboob_module(self):
        return self.module_weboob

    def set_weboob_module(self, name=None):
        self.module_weboob = name
        self.save()
        return self.module_weboob
    
    def __str__(self):
        return "%s" % self.name_of_bank

    class Meta:
        verbose_name = _('bank')
        verbose_name_plural = _('banks')
        ordering = ['name_of_bank']

    def get_absolute_url(self):
        return reverse('bank_detail', kwargs={'pk': self.pk})


class Accounts(models.Model):
    TYPE_UNKNOWN = 0            # Unknown
    TYPE_CHECKING = 1           # Transaction, everyday transactions
    TYPE_SAVINGS = 2            # Savings/Deposit, can be used for every banking
    TYPE_DEPOSIT = 3            # Term of Fixed Deposit, has time/amount constraints
    TYPE_LOAN = 4               # Loan account
    TYPE_MARKET = 5             # Stock market or other variable investments
    TYPE_JOINT = 6              # Joint account
    TYPE_CARD = 7               # Card account
    TYPE_LIFE_INSURANCE = 8     # Life insurances
    TYPE_PEE = 9                # Employee savings PEE
    TYPE_PERCO = 10             # Employee savings PERCO
    TYPE_ARTICLE_83 = 11        # Article 83
    TYPE_RSP = 12               # Employee savings RSP
    TYPE_PEA = 13               # Share savings
    TYPE_CAPITALISATION = 14    # Life Insurance capitalisation
    TYPE_PERP = 15              # Retirement savings
    TYPE_MADELIN = 16           # Complementary retirement savings
    TYPE_MORTGAGE = 17          # Mortgage
    TYPE_CONSUMER_CREDIT = 18   # Consumer credit
    TYPE_REVOLVING_CREDIT = 19  # Revolving credit

    TYPE_ACCOUNT_CHOICE = (
        (TYPE_UNKNOWN, 'Unknown'),
        (TYPE_CHECKING, 'Everyday transactions'),
        (TYPE_SAVINGS, 'Savings/Deposit'),
        (TYPE_DEPOSIT, 'Term of Fixed Deposit, has time/amount constraints'),
        (TYPE_LOAN, 'Loan account'),
        (TYPE_MARKET, 'Stock market or other variable investments'),
        (TYPE_JOINT, 'Joint account'),
        (TYPE_CARD, 'Card account'),
        (TYPE_LIFE_INSURANCE, 'Life insurances'),
        (TYPE_PEE, 'Employee savings PEE'),
        (TYPE_PERCO, 'Employee savings PERCO'),
        (TYPE_ARTICLE_83, 'Article 83'),
        (TYPE_RSP, 'Employee savings RSP'),
        (TYPE_PEA, 'Share savings'),
        (TYPE_CAPITALISATION, 'Life Insurance capitalisation'),
        (TYPE_PERP, 'Retirement savings'),
        (TYPE_MADELIN, 'Complementary retirement savings'),
        (TYPE_MORTGAGE, 'Mortgage'),
        (TYPE_CONSUMER_CREDIT, 'Consumer credit"'),
        (TYPE_REVOLVING_CREDIT, 'Revolving credit'),
    )

    name_of_account = models.CharField(
        'Name of the account',
        default='Name of bank account',
        max_length=256,
        help_text='Enter name of account'
    )

    num_of_account = models.CharField(
        'Account Id',
        default='Id',
        max_length=256,
        help_text='Enter number of account'
    )

    type_int_of_account = models.IntegerField(
        'Type of account (int)',  # use TYPE_* constants
        default=TYPE_UNKNOWN,
        choices=TYPE_ACCOUNT_CHOICE,
        help_text='Please select a type of account',
    )

    # TODO: A priori à supprimer: type_int_of_account suffit
    type_of_account = models.CharField(
        'Type of account',
        default=TYPE_UNKNOWN,
        # choices=TYPE_ACCOUNT_CHOICE,
        # default='Unknown',
        max_length=128,
        help_text='Enter type of account (this field will be deleted in next version)'
    )

    bank = models.ForeignKey(
        'Banks', 
        null=True, 
        blank=False, 
        on_delete=models.SET_NULL
    )

    # TODO: Il faut pouvoir affecter un User à un 'Bank account' (ce n'est pas le cas: tout le monde est 'owner'). Voir bank_edit en MultiSelect et faire un "add"
    owner_of_account = models.ManyToManyField(
        User, 
        related_name='user_of_account'
    )

    # Get lis of all users
    def get_users(self):
        return "\n".join([u.username for u in User.objects.all()])

    # Get list of users, owner of account
    def get_list_users(self):
        return "\n".join([u.username for u in self.owner_of_account.all()])
    
    def get_absolute_url(self):
        return reverse('account_detail', kwargs={'pk': self.pk})

    # TODO: To be tested
    def get_total_amount(self):
        total_amount = 0
        return Transactions.objects.filter(account__owner_of_account=self.request.user).aggregate(Sum('amount_of_transaction'))

    def __str__(self):
        return "%s" % self.name_of_account

    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')
        ordering = ['name_of_account']


class Transactions(models.Model):
    TYPE_UNKNOWN       = 0
    TYPE_TRANSFER      = 1
    TYPE_ORDER         = 2
    TYPE_CHECK         = 3
    TYPE_DEPOSIT       = 4
    TYPE_PAYBACK       = 5
    TYPE_WITHDRAWAL    = 6
    TYPE_CARD          = 7
    TYPE_LOAN_PAYMENT  = 8
    TYPE_BANK          = 9
    TYPE_CASH_DEPOSIT  = 10
    TYPE_CARD_SUMMARY  = 11
    TYPE_DEFERRED_CARD = 12

    TYPE_TRANSACTION_CHOICE = (
        (TYPE_UNKNOWN, 'Unknown'),
        (TYPE_TRANSFER, 'Transfer'),
        (TYPE_ORDER, 'Order'),
        (TYPE_CHECK,'Check'),
        (TYPE_DEPOSIT,'Deposit'),
        (TYPE_PAYBACK, 'Payback'),
        (TYPE_WITHDRAWAL, 'Withdrawal'),
        (TYPE_CARD, 'Credit card'),
        (TYPE_LOAN_PAYMENT, 'Loan payment'),
        (TYPE_BANK, 'Bank'),
        (TYPE_CASH_DEPOSIT, 'Cash deposit'),
        (TYPE_CARD_SUMMARY, 'Card summary'),
        (TYPE_DEFERRED_CARD, 'Deferred card'),
    )
    date_of_transaction = models.DateField(
        'Debit date on the bank statement',
        default=datetime.datetime.now
    )

    real_date_of_transaction = models.DateField(
        'Real date, when the payment has been made', # usually extracted from the label or from credit card info',
        default=datetime.datetime.now
    )

    value_date_of_transaction = models.DateField(
        'Value date, or accounting date; usually for professional accounts',
        default=datetime.datetime.now
    )

    type_int_of_transaction = models.IntegerField(
        'Type of transaction (int)',  # use TYPE_* constants
        default=TYPE_UNKNOWN,
        choices=TYPE_TRANSACTION_CHOICE,
    )

    # type_of_transaction is used to store weboob account category
    type_of_transaction = models.CharField(
        'Type of transaction',
        default='Unknown',
        # choices=TYPE_TRANSACTION_CHOICE,
        max_length=128
    )

    name_of_transaction = models.CharField(
        'Raw label of the transaction',
        max_length=256
    )

    label_of_transaction = models.CharField(
        'Pretty label',
        default='Pretty label',
        max_length=128
    )

    card_transaction = models.CharField(
        'Card number (if any)',
        default='Credit Card',
        blank=True,
        max_length=128
    )

    commission_of_transaction = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        verbose_name='Commission part on the transaction (in account currency)',
        blank=True,
        null=True
    )

    amount_of_transaction = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        verbose_name='Transaction amount',
        blank=True,
        null=True
    )

    currency_of_transaction = models.CharField(
        'Currency',
        default='EUR',
        max_length=3
    )

    # Date of creation of the transaction in the database server (not in the bank)
    creation_date = models.DateField(
        'Creation date of the transaction in  database',
        default=datetime.datetime.now
    )

    account = models.ForeignKey(
        Accounts,
        # null=True,
        # blank=True,
        related_name='transactions',
        on_delete=models.CASCADE
    )

    unique_id_of_transaction = models.CharField(
        'Unique Id based on date_of_transaction, amount_of_transaction and name_of_transaction',
        default='unique_id',
        max_length=128
    )

    category_of_transaction = models.ForeignKey(
        Category,
        null=True,
        # default='Budget',
        blank=True,
        on_delete=models.CASCADE
    )

    key_words = ArrayField(models.CharField(max_length=256, blank=True, null=True), blank=True, null=True)

    def get_absolute_url(self):
        return reverse('transaction_detail', kwargs={'pk': self.pk})

    def unique_id(self, seen=None, account_id=None):
        """

gesfipe/managegesfi/models.py
from django.db import models

# Create your models here.

gesfipe/categories/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from .models import Tag
from gesfipe.categories.models import Category


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('tag', 'is_new_tag', 'will_be_used_as_tag', 'category',)

    # widgets = {
    #            'category':TreeNodeChoiceField(queryset=Category.objects.all()),
    #        }
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())
    category = TreeNodeChoiceField(queryset=Category.objects.all(), level_indicator=u'+--')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = {'name', 'description', 'amount'}

gesfipe/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

gesfipe/templates/banksandaccounts/account_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load crispy_forms_tags %}


{% block head %}
    <link href="{% static 'css/search.css' %}" rel="stylesheet">
    <script src="{% static 'js/search.js' %}"></script>
{% endblock head %}

{% block title %}
    {{account.name_of_account}}
{% endblock %}

{% block heading %}
    <h2>{% trans 'Account detail:' %}</h2>
    <h4>{% trans 'Name of bank:' %} {{account.bank.name_of_bank}}</h4>
    <h4>{% trans 'Name of account:' %} {{account.name_of_account}}</h4>
{% endblock heading %}

{% block content %}

<table class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Num</th>
        <th>Type</th>
        <th>Bank</th>
    </tr>
    </thead>

    <tbody>
      <tr>
          {# <td><a href="/account_edit/{{account.id}}/">{{ account.name_of_account }}</a></td> #}
          <td><a href="{% url 'banksandaccounts:account_edit' account.id %}">{{ account.name_of_account }}</a></td>
          <td>{{ account.num_of_account }}</td>
          <td>{{ account.get_type_int_of_account_display }}</td>
          <td>{{ account.bank.name_of_bank }}</td>
      </tr>
    </tbody>

</table>

{% endblock content %}


{% block sidesearch %}

{% endblock sidesearch %}


{% block sidebar %}

{% endblock %}

gesfipe/templates/banksandaccounts/accounts_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'List of accounts' %}
{% endblock %}


{% block heading %}

{% endblock heading %}


{% block content %}
    {% if accounts_list %}
        <table class="table table-striped ">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Num. </th>
                    <th>Total amount</th>
                    <th>Type</th>
                    <th>Bank</th>
                    <th>Owner(s)</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts_info %}
                    <tr>
                        <td><a href="{% url 'banksandaccounts:account_edit' account.id %}">{{ account.name_of_account }}</a></td>
                        <td><a href="{% url 'banksandaccounts:account_list' account.id %}">{{ account.num_of_account }}</a></td>
                        <td style="text-align: center">{{ account.total_amount_by_account}}</td>
                        <td>{{ account.get_type_int_of_account_display }}</td>
                        <td>{{ account.bank.name_of_bank }}</td>
                        <td>
                            {% for u in account.owner_of_account.all %}
                                {{u}}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tbody>
                <tr>
                    <td></td>
                    <td><b>Total : </b></td>
                    <td style="text-align: center">
                        <b>
                            {{ account_total.amount_of_transaction__sum }}
                        </b>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    {% else %}
        <p>There are no available account for this user.</p>
    {% endif %}

{% endblock %}

{% block sidebar %}
    <div class="row">

    </div>
{% endblock %}

gesfipe/templates/banksandaccounts/bank_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block title %}
    {% if create %} - Create{% else %} - Edit{% endif %} bank {{ form.instance.name }}
{% endblock %}

{% block heading %}
    {% if create %}
        <h2>Create bank</h2>
    {% else %}
        <h2>Edit bank:</h2>
        <h4><i>{{ bank.name_of_bank }}</i></h4>
    {% endif %}
{% endblock %}

{% block content %}
    {% if create %}
        {% url "bank_create" as action_url %}
    {% else %}
        {% url "bank_edit" pk=form.instance.pk as action_url %}
    {% endif %}
    <form action="{{ action_url }}" method="post" accept-charset="utf-8">
        {{ form|crispy }}
        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary" value="Save"></p>
    </form>
{% endblock %}


{% block sidesearch %}

{% endblock sidesearch %}


{% block sidebar %}

{% endblock %}

gesfipe/templates/banksandaccounts/banks_and_accounts_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}

{% block heading %}
    <h2>{% trans 'List of Banks and Accounts' %}</h2>
    <h4>{% trans 'Total amount:' %} {{account_total.total}}</h4>
{% endblock heading %}

{% block content %}
  <div class="row">
    {% for bank in banks_list %}
        {% for account in accounts_info %}
            {% if account.bank == bank %}
            <div class="col-12 col-sm-12 col-md-9 col-lg-4">
                <div class="card"
                     data-toggle="tooltip"
                     data-placement="top"
                     title="Click to get list of transactions related to this account">
                  <a href="{% url 'banksandaccounts:account_list' account.id %}">
                    <img class="card-img-top"
                         src="{% static 'images/banksandaccounts/pexels-photo-196658.jpeg' %}"
                         alt="Card image cap">
                  </a>
                    <div class="card-body">
                      <h4 class="card-title">Account name: <br><a href="{% url 'banksandaccounts:account_detail' account.id %}"> {{account.name_of_account}}</a></h4>
                      <h6 class="card-subtitle mb-2 text-muted"><a href="{% url 'banksandaccounts:bank_detail' bank.id %}">{{bank}}</a> - Type of account: {{account.get_type_int_of_account_display}}</h6>
                        <p class="card-text">
                            <br> Total :
                                {% if account.total_amount_by_account >= 0 %}
                                    <span class="font-blue"><strong>{{account.total_amount_by_account}}</strong></span>
                                {% else %}
                                    <span class="font-red"><strong>{{account.total_amount_by_account}}</strong></span>
                                {% endif %}
                            <br> Transaction Mini:
                                {% if account.min_amount_by_account < 0 %}
                                    <span class="label label-danger"> {{account.min_amount_by_account}} </span>
                                {% else %}
                                    <span class="label label-primary"> {{account.min_amount_by_account}} </span>
                                {% endif %}
                            <br> Transaction Maxi:
                                {% if account.max_amount_by_account < 0 %}
                                    <span class="label label-danger"> {{account.max_amount_by_account}} </span>
                                {% else %}
                                    <span class="label label-primary"> {{account.max_amount_by_account}} </span>
                                {% endif %}
                            <br> Number of transactions: <span class="label label-default">{{account.num_transac_by_account}}</span>
                            <br>
                        </p>
                    </div>
                    <div class="card-footer">
                      <a href="{% url 'banksandaccounts:account_list' account.id %}">Transactions</a>
                      {# <a href="#" class="card-link">Another link</a> #}
                    </div>
                </div>
                <br>
            </div>
            {% endif %}
        {% endfor %}
    {% endfor %}
  </div>
{% endblock content %}


{% block sidesearch %}

  {% include 'banksandaccounts/sidebar_search.html' %}

{% endblock sidesearch %}


{% block sidebar %}

{% endblock sidebar %}

gesfipe/templates/banksandaccounts/banks_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Banks deletion' %}
{% endblock %}


{% block heading %}

{% endblock heading %}


{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

{% block sidebar %}
    <div class="row">

    </div>
{% endblock %}

gesfipe/templates/banksandaccounts/sidebar_list_of_accounts.html
{% load i18n %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load crispy_forms_tags %}

{% for bank in banks_list %}
  {% for account in all_accounts %}
    {% if account.bank == bank %}
      <div class="card">
        <a href="{% url 'banksandaccounts:account_list' account.id %}">
          <!-- TODO: How to send "name of bank" and "name of account" with link of sidebar_list -->
          <img class="card-img-top"
               src="{% static 'images/banksandaccounts/pexels-photo-196658.jpeg' %}"
               alt="Card image cap">
        </a>
        <div class="card-body">
          <h4 class="card-title">Account name: <a href="{% url 'banksandaccounts:account_detail' account.id %}"> {{account.name_of_account}}</a></h4>
          <h6 class="card-subtitle mb-2 text-muted"><a href="{% url 'banksandaccounts:bank_detail' bank.id %}">{{bank}}</a> - Type of account: {{account.get_type_int_of_account_display}}</h6>
          <p class="card-text">
            <i>
              <br>Total :
              {% if account.total_amount_by_account >= 0 %}
              <span class="font-blue"><strong>{{account.total_amount_by_account}}</strong></span>
              {% else %}
              <span class="font-red"><strong>{{account.total_amount_by_account}}</strong></span>
              {% endif %}
              <br>Number of transactions: <span class="label label-default"> {{account.num_transac_by_account}}</span>
            </i>
          </p>
        </div>
        <div class="card-footer">
          {# <a href="/transaction_create/">Create new transaction</a> #}
          <a href="{% url 'banksandaccounts:transaction_create' %}">Create new transaction</a>
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endfor %}

gesfipe/templates/banksandaccounts/sidebar_search.html
{% load i18n %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load crispy_forms_tags %}

  <div class="content">
  {% if not hide_search %}
    <form class="search-sidebar" role="search" action="{% url 'managegesfi:search' %}">
      <div class="input-group">
        <input type="text" class="form-control" name="q" placeholder="Search">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-primary search-sidebar">
              Submit
              <!-- <span class="glyphicon glyphicon-search"></span> -->
            </button>
          </span>
      </div>
    </form>
  {% endif %}
  </div>